---
title: "04-Robin Hood"
output: html_notebook
---

# Robin Hood: 
Estamos en plena competición para ganar el concurso de tiro con arco en Sherwood. Con nuestro arco y flechas disparamos sobre una diana e intentamos acertar lo más cerca posible del centro. 

El centro de la diana viene representado por los valores (0, 0) en los ejes de coordenadas. 

## Objetivos: 
* estructuras de datos: listas, conjuntos, tuplas
* operadores lógicos: if-elif-else
* bucle: while/for
* cálculo de mínimo (sorting opcional)

## Descripción: 
En el espacio de 2 dimensiones un punto se puede definir por un par de valores que corresponden a la coordenada horizontal (x) y a la vertical (y). El espacio puede quedar dividido en 4 zonas (cuadrantes): Q1, Q2, Q3, Q4. Cuyo punto de unión único es el punto (0, 0). 

Si un punto se encuentra en Q1 tanto su coordenada x como la y son positivas. Te dejo un enlace a wikipedia para que te familiarices con estos cuadrantes. 

https://es.wikipedia.org/wiki/Coordenadas_cartesianas

https://es.wikipedia.org/wiki/Distancia_euclidiana

## Tareas
1. Robin Hood es famoso por acertar a una flecha con otra flecha. ¿Lo ha conseguido? 
2. Calcula cuántos flechazos han caido en cada cuadrante. 
3. Halla el punto más cercano al centro. Calcula su distancia al centro
4. Si la diana tiene un radio de 9, calcula el número de flechas que hay que recoger al bosque. 

## RESPUESTA

```{r}
puntos  <-  list(c(4,5), c(-0,2), c(4,7), c(1,-3), c(3,-2), c(4,5), 
          c(3,2), c(5,7), c(-5,7), c(2,2), c(-4,5), c(0,-2), 
          c(-4,7), c(-1,3), c(-3,2), c(-4,-5), c(-3,2), 
          c(5,7), c(5,7), c(2,2), c(9, 9), c(-8, -9))

# 1. Robin Hood es famoso por acertar a una flecha con otra flecha. ¿Lo ha conseguido? 


# 2. Calcula cuántos flechazos han caido en cada cuadrante. 


# 3. Halla el punto más cercano al centro. Calcula su distancia al centro
# Definir una función que calcula la distancia al centro puede servir de ayuda. 


# 4. Si la diana tiene un radio de 9, calcula el número de flechas que hay que recoger al bosque.
```

