---
title: "01_lab_Lubridate"
author: "Marco R."
date: "6/4/2021"
output: html_document
---

# Prácticas con manipulación de fechas con `Lubridate`

```{r}
library(tidyverse)
library(lubridate)
```


```{r}
# Carga de los datos
library(nycflights13)
```


```{r}
# Para revisar que funciona la librería lubridate
today()
```


```{r}
now()
```


## La función de Lubridate `ymd`

```{r}
# Transformar fechas en formato string
ymd("2021-04-06")
```


```{r}
typeof(ymd("2021-04-06"))
```


```{r}
# Damos el format Month-Day-Year
mdy("April, 6th, 2021")
```


```{r}
# Formato Day-Month-Year
dmy("06-April-2021")
```


```{r}
# o en español
dmy("6 Abril 2021")
```


```{r}
ymd(20210406)
```


## Función Lubridate `ymd_hms`

```{r}
ymd_hms("2021-04-06 19:55:11") # lo convierte en timezone UTC
```



```{r}
mdy_hm("04/06/21 19:55") # siempre lo convierte en timezone UTC 
```


```{r}
# En caso de aplicar el timezone
ymd_hms("2021-04-06 19:55:11", tz = "Europe/Madrid")
```



```{r}
# Aplicamos el timezone de Australia
ymd_hms("2021-04-06 19:55:11", tz = "Australia/Sydney")
```


```{r}
ymd("2021-04-06", tz = "Europe/Madrid") # siempre debemos indicarle el continente/ciudad
```


## Aplicamos estas funciones a nuestro dataset

```{r}
flights %>%
  select(year, month, day, hour, minute)
```


### Aplicamos el formato Lubridate a nuestro dataset

```{r}
flights %>%
  select(year, month, day, hour, minute) %>%
  mutate(
    departure = make_datetime(year, month, day, hour, minute, tz="GMT")
  )
```



```{r}
# creamos la transformación del datetime en variables dep_time y arr_time
make_datetime_100 <- function(year, month, day, time) {
  make_datetime(year, month, day, time %/% 100, time %% 100)
}
```


```{r}
# Aplicamos la función anterior a nuestro dataset
flights_dt <- flights %>%
  filter(!is.na(dep_time), !is.na(arr_time)) %>%
  mutate(
    dep_time = make_datetime_100(year, month, day, dep_time),
    arr_time = make_datetime_100(year, month, day, arr_time),
    sched_dep_time = make_datetime_100(
      year, month, day, sched_dep_time
    ),
    sched_arr_time = make_datetime_100(
      year, month, day, sched_arr_time
    ),
    air_time = make_datetime_100(year, month, day, air_time)
  ) %>%
  select(origin, dest, ends_with("delay"), ends_with("time"))

```


```{r}
# revisamos la estructura
str(flights_dt)
```

```{r}
# Visualización del dataset con ggplot2
flights_dt %>%
  ggplot(aes(dep_time)) +
  geom_freqpoly(binwidth = 86400) # este sería el valor correspondiente a los segundos de un día
  
    
```



```{r}
# Visualizamos por día
flights_dt %>%
  filter(dep_time < ymd(20130102)) %>%
  ggplot(aes(dep_time)) + 
  geom_freqpoly(binwidth = 600) # son segundos igual a 10 minutos
```


## Transformación de otro tipo de formato fecha

```{r}
as_datetime((today()))
```


```{r}
as_date(now())
```


```{r}
# En muchos casos tenemos un formato del tipo UNIX - con el formato estándar 1970-01-01
as_datetime(60 * 60 * 10) 
```


```{r}
as_datetime(365 * 10 + 2) #  año 1980
```


## Componentes de un `datetime`

```{r}
datetime <- ymd_hms("2021-04-06 20:22:20")
datetime
```

```{r}
# recogemos el valor year
year(datetime)
```


```{r}
# recogemos el valor month
month(datetime)
```

```{r}
# recogemos el valor day
mday(datetime)
```


```{r}
# recogemos el valor día del año
yday(datetime)
```


```{r}
# recogemos el valor del día de la semana
wday(datetime) # teniendo en cuenta que comienza por 1 = Sunday
```


```{r}
# Podemos asignarle atributos a month() de forma literal
month(datetime, label = TRUE)
```


```{r}
# Podemos asignarle atributos a wday() de forma literal
wday(datetime, label = TRUE, abbr = FALSE)
```


```{r}
# días de la semana de LUN - DOM en italiano
wday(datetime, label = TRUE, abbr = FALSE, locale = "Italian", week_start = 1)
```

```{r}
# meses del año 
month(datetime, label = TRUE, abbr = FALSE, locale = "French")
```

## Representación del `datetime`

```{r}
# Visualizamos los días de la semana aplicado a flights
flights_dt %>%
  mutate(wday = wday(dep_time, label = TRUE, abbr = FALSE, locale = 'german', week_start = 1)) %>%
  ggplot(aes(x = wday)) +
  geom_bar()
```

