---
title: "pra_matrices"
output: html_notebook
---

## Prácticas con las matrices

#### Descripción

```
'''
# Taquilla de Star Wars: En Millones de dólares (USD)!
# Primer elemento taquilla en EEUU, segundo taquilla fuera de EEUU.
new_hope <- c(460.998, 314.400)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.800)
'''
```

```{r}
# Crear una matriz
```




```{r}
# Como evaluamos una matriz
is.matrix()
```


```{r}
typeof()
```


```{r}
# Creamos el encabezado, creamos primero los vectores
peliculas <- c("New Hope",
               "Empire Strikes",
               "Return Jedi")

# Para los paises EEUU y no-EEUU

```



```{r}
# Sumamos las taquillas por fila

```



```{r}
# suma de las taquillas globales
```


```{r}
# Creamos una nueva matriz

taquillas2 <- c(474.5, 552.5, 310.7, 338.7, 380.3, 468.5)
nombres2 <- c("The Phantom Menace", "Attack of the Clones", "Revenge of the Sith")

```



```{r}
# combinación de matrices
```



```{r}
# total de las taquillas de US y noUS
```



```{r}
# Promedio no-US
```


```{r}
# Promedio US
```



```{r}
# Promedio de las 3 primeras peliculas US
```



```{r}
# Buscamos el max de las taquillas de no-US
```


```{r}
# Buscamos el promedio de no-US pero de forma alterna 
```


```{r}
# Buscamos los resultados de la segunda fila, segunda columna
```


```{r}
# Buscamos los resultados de la segunda columna
```



```{r}
# Buscamos los resultados de la cuarta fila
```


```{r}
# Buscamos el min de la quinta fila
```


```{r}
# Desviación estandar de la segunda columna
```












